<?php

declare(strict_types=1);

namespace Sirix\Money;

use Sirix\Money\Exception\InvalidArgumentException;

/**
 * Enum representing fiat currency codes.
 */
enum FiatCurrencyCode: string
{
    // Fiat currencies
    case Aed = 'AED';
    case Afn = 'AFN';
    case All = 'ALL';
    case Amd = 'AMD';
    case Ang = 'ANG';
    case Aoa = 'AOA';
    case Ars = 'ARS';
    case Aud = 'AUD';
    case Awg = 'AWG';
    case Azn = 'AZN';
    case Bam = 'BAM';
    case Bbd = 'BBD';
    case Bdt = 'BDT';
    case Bgn = 'BGN';
    case Bhd = 'BHD';
    case Bif = 'BIF';
    case Bmd = 'BMD';
    case Bnd = 'BND';
    case Bob = 'BOB';
    case Bov = 'BOV';
    case Brl = 'BRL';
    case Bsd = 'BSD';
    case Btn = 'BTN';
    case Bwp = 'BWP';
    case Byn = 'BYN';
    case Bzd = 'BZD';
    case Cad = 'CAD';
    case Cdf = 'CDF';
    case Che = 'CHE';
    case Chf = 'CHF';
    case Chw = 'CHW';
    case Clf = 'CLF';
    case Clp = 'CLP';
    case Cny = 'CNY';
    case Cop = 'COP';
    case Cou = 'COU';
    case Crc = 'CRC';
    case Cuc = 'CUC';
    case Cup = 'CUP';
    case Cve = 'CVE';
    case Czk = 'CZK';
    case Djf = 'DJF';
    case Dkk = 'DKK';
    case Dop = 'DOP';
    case Dzd = 'DZD';
    case Egp = 'EGP';
    case Ern = 'ERN';
    case Etb = 'ETB';
    case Eur = 'EUR';
    case Fjd = 'FJD';
    case Fkp = 'FKP';
    case Gbp = 'GBP';
    case Gel = 'GEL';
    case Ghs = 'GHS';
    case Gip = 'GIP';
    case Gmd = 'GMD';
    case Gnf = 'GNF';
    case Gtq = 'GTQ';
    case Gyd = 'GYD';
    case Hkd = 'HKD';
    case Hnl = 'HNL';
    case Htg = 'HTG';
    case Huf = 'HUF';
    case Idr = 'IDR';
    case Ils = 'ILS';
    case Inr = 'INR';
    case Iqd = 'IQD';
    case Irr = 'IRR';
    case Isk = 'ISK';
    case Jmd = 'JMD';
    case Jod = 'JOD';
    case Jpy = 'JPY';
    case Kes = 'KES';
    case Kgs = 'KGS';
    case Khr = 'KHR';
    case Kmf = 'KMF';
    case Kpw = 'KPW';
    case Krw = 'KRW';
    case Kwd = 'KWD';
    case Kyd = 'KYD';
    case Kzt = 'KZT';
    case Lak = 'LAK';
    case Lbp = 'LBP';
    case Lkr = 'LKR';
    case Lrd = 'LRD';
    case Lsl = 'LSL';
    case Lyd = 'LYD';
    case Mad = 'MAD';
    case Mdl = 'MDL';
    case Mga = 'MGA';
    case Mkd = 'MKD';
    case Mmk = 'MMK';
    case Mnt = 'MNT';
    case Mop = 'MOP';
    case Mru = 'MRU';
    case Mur = 'MUR';
    case Mvr = 'MVR';
    case Mwk = 'MWK';
    case Mxn = 'MXN';
    case Mxv = 'MXV';
    case Myr = 'MYR';
    case Mzn = 'MZN';
    case Nad = 'NAD';
    case Ngn = 'NGN';
    case Nio = 'NIO';
    case Nok = 'NOK';
    case Npr = 'NPR';
    case Nzd = 'NZD';
    case Omr = 'OMR';
    case Pab = 'PAB';
    case Pen = 'PEN';
    case Pgk = 'PGK';
    case Php = 'PHP';
    case Pkr = 'PKR';
    case Pln = 'PLN';
    case Pyg = 'PYG';
    case Qar = 'QAR';
    case Ron = 'RON';
    case Rsd = 'RSD';
    case Rub = 'RUB';
    case Rwf = 'RWF';
    case Sar = 'SAR';
    case Sbd = 'SBD';
    case Scr = 'SCR';
    case Sdg = 'SDG';
    case Sek = 'SEK';
    case Sgd = 'SGD';
    case Shp = 'SHP';
    case Sle = 'SLE';
    case Sos = 'SOS';
    case Srd = 'SRD';
    case Ssp = 'SSP';
    case Stn = 'STN';
    case Svc = 'SVC';
    case Syp = 'SYP';
    case Szl = 'SZL';
    case Thb = 'THB';
    case Tjs = 'TJS';
    case Tmt = 'TMT';
    case Tnd = 'TND';
    case Top = 'TOP';
    case Try = 'TRY';
    case Ttd = 'TTD';
    case Twd = 'TWD';
    case Tzs = 'TZS';
    case Uah = 'UAH';
    case Ugx = 'UGX';
    case Usd = 'USD';
    case Usn = 'USN';
    case Uyi = 'UYI';
    case Uyu = 'UYU';
    case Uyw = 'UYW';
    case Uzs = 'UZS';
    case Ved = 'VED';
    case Ves = 'VES';
    case Vnd = 'VND';
    case Vuv = 'VUV';
    case Wst = 'WST';
    case Xaf = 'XAF';
    case Xcd = 'XCD';
    case Xof = 'XOF';
    case Xpf = 'XPF';
    case Yer = 'YER';
    case Zar = 'ZAR';
    case Zmw = 'ZMW';
    case Zwg = 'ZWG';

    /**
     * Returns the number of decimal digits for this currency.
     */
    public function digits(): int
    {
        return match ($this) {
            self::Bhd, self::Iqd, self::Jod, self::Kwd, self::Lyd, self::Omr, self::Tnd => 3,
            self::Bif, self::Clp, self::Djf, self::Gnf, self::Isk, self::Jpy, self::Kmf, self::Krw, self::Xpf,
            self::Xof, self::Xaf, self::Vuv, self::Vnd, self::Ugx, self::Rwf, self::Pyg => 0,
            self::Clf => 4,
            default => 2,
        };
    }

    /**
     * Returns the numeric code for this currency.
     */
    public function numericCode(): int
    {
        return match ($this) {
            self::Aed => 784,
            self::Afn => 971,
            self::All => 8,
            self::Amd => 51,
            self::Ang => 532,
            self::Aoa => 973,
            self::Ars => 32,
            self::Aud => 36,
            self::Awg => 533,
            self::Azn => 944,
            self::Bam => 977,
            self::Bbd => 52,
            self::Bdt => 50,
            self::Bgn => 975,
            self::Bhd => 48,
            self::Bif => 108,
            self::Bmd => 60,
            self::Bnd => 96,
            self::Bob => 68,
            self::Bov => 984,
            self::Brl => 986,
            self::Bsd => 44,
            self::Btn => 64,
            self::Bwp => 72,
            self::Byn => 933,
            self::Bzd => 84,
            self::Cad => 124,
            self::Cdf => 976,
            self::Che => 947,
            self::Chf => 756,
            self::Chw => 948,
            self::Clf => 990,
            self::Clp => 152,
            self::Cny => 156,
            self::Cop => 170,
            self::Cou => 970,
            self::Crc => 188,
            self::Cuc => 931,
            self::Cup => 192,
            self::Cve => 132,
            self::Czk => 203,
            self::Djf => 262,
            self::Dkk => 208,
            self::Dop => 214,
            self::Dzd => 12,
            self::Egp => 818,
            self::Ern => 232,
            self::Etb => 230,
            self::Eur => 978,
            self::Fjd => 242,
            self::Fkp => 238,
            self::Gbp => 826,
            self::Gel => 981,
            self::Ghs => 936,
            self::Gip => 292,
            self::Gmd => 270,
            self::Gnf => 324,
            self::Gtq => 320,
            self::Gyd => 328,
            self::Hkd => 344,
            self::Hnl => 340,
            self::Htg => 332,
            self::Huf => 348,
            self::Idr => 360,
            self::Ils => 376,
            self::Inr => 356,
            self::Iqd => 368,
            self::Irr => 364,
            self::Isk => 352,
            self::Jmd => 388,
            self::Jod => 400,
            self::Jpy => 392,
            self::Kes => 404,
            self::Kgs => 417,
            self::Khr => 116,
            self::Kmf => 174,
            self::Kpw => 408,
            self::Krw => 410,
            self::Kwd => 414,
            self::Kyd => 136,
            self::Kzt => 398,
            self::Lak => 418,
            self::Lbp => 422,
            self::Lkr => 144,
            self::Lrd => 430,
            self::Lsl => 426,
            self::Lyd => 434,
            self::Mad => 504,
            self::Mdl => 498,
            self::Mga => 969,
            self::Mkd => 807,
            self::Mmk => 104,
            self::Mnt => 496,
            self::Mop => 446,
            self::Mru => 929,
            self::Mur => 480,
            self::Mvr => 462,
            self::Mwk => 454,
            self::Mxn => 484,
            self::Mxv => 979,
            self::Myr => 458,
            self::Mzn => 943,
            self::Nad => 516,
            self::Ngn => 566,
            self::Nio => 558,
            self::Nok => 578,
            self::Npr => 524,
            self::Nzd => 554,
            self::Omr => 512,
            self::Pab => 590,
            self::Pen => 604,
            self::Pgk => 598,
            self::Php => 608,
            self::Pkr => 586,
            self::Pln => 985,
            self::Pyg => 600,
            self::Qar => 634,
            self::Ron => 946,
            self::Rsd => 941,
            self::Rub => 643,
            self::Rwf => 646,
            self::Sar => 682,
            self::Sbd => 90,
            self::Scr => 690,
            self::Sdg => 938,
            self::Sek => 752,
            self::Sgd => 702,
            self::Shp => 654,
            self::Sle => 925,
            self::Sos => 706,
            self::Srd => 968,
            self::Ssp => 728,
            self::Stn => 930,
            self::Svc => 222,
            self::Syp => 760,
            self::Szl => 748,
            self::Thb => 764,
            self::Tjs => 972,
            self::Tmt => 934,
            self::Tnd => 788,
            self::Top => 776,
            self::Try => 949,
            self::Ttd => 780,
            self::Twd => 901,
            self::Tzs => 834,
            self::Uah => 980,
            self::Ugx => 800,
            self::Usd => 840,
            self::Usn => 997,
            self::Uyi => 940,
            self::Uyu => 858,
            self::Uyw => 927,
            self::Uzs => 860,
            self::Ved => 926,
            self::Ves => 928,
            self::Vnd => 704,
            self::Vuv => 548,
            self::Wst => 882,
            self::Xaf => 950,
            self::Xcd => 951,
            self::Xof => 952,
            self::Xpf => 953,
            self::Yer => 886,
            self::Zar => 710,
            self::Zmw => 967,
            self::Zwg => 924,
        };
    }

    /**
     * @return array<string, bool|int|string>
     */
    public function getParams(): array
    {
        return [
            'name' => $this->name(),
            'digits' => $this->digits(),
            'isCrypto' => false,
            'numericCode' => $this->numericCode(),
        ];
    }

    /**
     * @throws InvalidArgumentException
     */
    public static function fromNumericCode(int $numericCode): self
    {
        return match ($numericCode) {
            784 => self::Aed,
            971 => self::Afn,
            8 => self::All,
            51 => self::Amd,
            532 => self::Ang,
            973 => self::Aoa,
            32 => self::Ars,
            36 => self::Aud,
            533 => self::Awg,
            944 => self::Azn,
            977 => self::Bam,
            52 => self::Bbd,
            50 => self::Bdt,
            975 => self::Bgn,
            48 => self::Bhd,
            108 => self::Bif,
            60 => self::Bmd,
            96 => self::Bnd,
            68 => self::Bob,
            984 => self::Bov,
            986 => self::Brl,
            44 => self::Bsd,
            64 => self::Btn,
            72 => self::Bwp,
            933 => self::Byn,
            84 => self::Bzd,
            124 => self::Cad,
            976 => self::Cdf,
            947 => self::Che,
            756 => self::Chf,
            948 => self::Chw,
            990 => self::Clf,
            152 => self::Clp,
            156 => self::Cny,
            170 => self::Cop,
            970 => self::Cou,
            188 => self::Crc,
            931 => self::Cuc,
            192 => self::Cup,
            132 => self::Cve,
            203 => self::Czk,
            262 => self::Djf,
            208 => self::Dkk,
            214 => self::Dop,
            12 => self::Dzd,
            818 => self::Egp,
            232 => self::Ern,
            230 => self::Etb,
            978 => self::Eur,
            242 => self::Fjd,
            238 => self::Fkp,
            826 => self::Gbp,
            981 => self::Gel,
            936 => self::Ghs,
            292 => self::Gip,
            270 => self::Gmd,
            324 => self::Gnf,
            320 => self::Gtq,
            328 => self::Gyd,
            344 => self::Hkd,
            340 => self::Hnl,
            332 => self::Htg,
            348 => self::Huf,
            360 => self::Idr,
            376 => self::Ils,
            356 => self::Inr,
            368 => self::Iqd,
            364 => self::Irr,
            352 => self::Isk,
            388 => self::Jmd,
            400 => self::Jod,
            392 => self::Jpy,
            404 => self::Kes,
            417 => self::Kgs,
            116 => self::Khr,
            174 => self::Kmf,
            408 => self::Kpw,
            410 => self::Krw,
            414 => self::Kwd,
            136 => self::Kyd,
            398 => self::Kzt,
            418 => self::Lak,
            422 => self::Lbp,
            144 => self::Lkr,
            430 => self::Lrd,
            426 => self::Lsl,
            434 => self::Lyd,
            504 => self::Mad,
            498 => self::Mdl,
            969 => self::Mga,
            807 => self::Mkd,
            104 => self::Mmk,
            496 => self::Mnt,
            446 => self::Mop,
            929 => self::Mru,
            480 => self::Mur,
            462 => self::Mvr,
            454 => self::Mwk,
            484 => self::Mxn,
            979 => self::Mxv,
            458 => self::Myr,
            943 => self::Mzn,
            516 => self::Nad,
            566 => self::Ngn,
            558 => self::Nio,
            578 => self::Nok,
            524 => self::Npr,
            554 => self::Nzd,
            512 => self::Omr,
            590 => self::Pab,
            604 => self::Pen,
            598 => self::Pgk,
            608 => self::Php,
            586 => self::Pkr,
            985 => self::Pln,
            600 => self::Pyg,
            634 => self::Qar,
            946 => self::Ron,
            941 => self::Rsd,
            643 => self::Rub,
            646 => self::Rwf,
            682 => self::Sar,
            90 => self::Sbd,
            690 => self::Scr,
            938 => self::Sdg,
            752 => self::Sek,
            702 => self::Sgd,
            654 => self::Shp,
            925 => self::Sle,
            706 => self::Sos,
            968 => self::Srd,
            728 => self::Ssp,
            930 => self::Stn,
            222 => self::Svc,
            760 => self::Syp,
            748 => self::Szl,
            764 => self::Thb,
            972 => self::Tjs,
            934 => self::Tmt,
            788 => self::Tnd,
            776 => self::Top,
            949 => self::Try,
            780 => self::Ttd,
            901 => self::Twd,
            834 => self::Tzs,
            980 => self::Uah,
            800 => self::Ugx,
            840 => self::Usd,
            997 => self::Usn,
            940 => self::Uyi,
            858 => self::Uyu,
            927 => self::Uyw,
            860 => self::Uzs,
            926 => self::Ved,
            928 => self::Ves,
            704 => self::Vnd,
            548 => self::Vuv,
            882 => self::Wst,
            950 => self::Xaf,
            951 => self::Xcd,
            952 => self::Xof,
            953 => self::Xpf,
            886 => self::Yer,
            710 => self::Zar,
            967 => self::Zmw,
            924 => self::Zwg,
            default => throw new InvalidArgumentException("Unknown numeric code: {$numericCode}"),
        };
    }

    /**
     * Returns the currency type.
     */
    public function type(): CurrencyType
    {
        return CurrencyType::Fiat;
    }

    /**
     * Returns the full name of the currency.
     */
    public function name(): string
    {
        return match ($this) {
            self::Aed => 'United Arab Emirates Dirham',
            self::Afn => 'Afghan Afghani',
            self::All => 'Albanian Lek',
            self::Amd => 'Armenian Dram',
            self::Ang => 'Netherlands Antillean Guilder',
            self::Aoa => 'Angolan Kwanza',
            self::Ars => 'Argentine Peso',
            self::Aud => 'Australian Dollar',
            self::Awg => 'Aruban Florin',
            self::Azn => 'Azerbaijani Manat',
            self::Bam => 'Bosnia and Herzegovina Convertible Mark',
            self::Bbd => 'Barbados Dollar',
            self::Bdt => 'Bangladeshi Taka',
            self::Bgn => 'Bulgarian Lev',
            self::Bhd => 'Bahraini Dinar',
            self::Bif => 'Burundian Franc',
            self::Bmd => 'Bermudian Dollar',
            self::Bnd => 'Brunei Dollar',
            self::Bob => 'Boliviano',
            self::Bov => 'Bolivian Mvdol',
            self::Brl => 'Brazilian Real',
            self::Bsd => 'Bahamian Dollar',
            self::Btn => 'Bhutanese Ngultrum',
            self::Bwp => 'Botswana Pula',
            self::Byn => 'Belarusian Ruble',
            self::Bzd => 'Belize Dollar',
            self::Cad => 'Canadian Dollar',
            self::Cdf => 'Congolese Franc',
            self::Che => 'WIR Euro',
            self::Chf => 'Swiss Franc',
            self::Chw => 'WIR Franc',
            self::Clf => 'Unidad de Fomento',
            self::Clp => 'Chilean Peso',
            self::Cny => 'Chinese Yuan',
            self::Cop => 'Colombian Peso',
            self::Cou => 'Unidad de Valor Real',
            self::Crc => 'Costa Rican Colón',
            self::Cuc => 'Cuban Convertible Peso',
            self::Cup => 'Cuban Peso',
            self::Cve => 'Cape Verdean Escudo',
            self::Czk => 'Czech Koruna',
            self::Djf => 'Djiboutian Franc',
            self::Dkk => 'Danish Krone',
            self::Dop => 'Dominican Peso',
            self::Dzd => 'Algerian Dinar',
            self::Egp => 'Egyptian Pound',
            self::Ern => 'Eritrean Nakfa',
            self::Etb => 'Ethiopian Birr',
            self::Eur => 'Euro',
            self::Fjd => 'Fiji Dollar',
            self::Fkp => 'Falkland Islands Pound',
            self::Gbp => 'Pound Sterling',
            self::Gel => 'Georgian Lari',
            self::Ghs => 'Ghanaian Cedi',
            self::Gip => 'Gibraltar Pound',
            self::Gmd => 'Gambian Dalasi',
            self::Gnf => 'Guinean Franc',
            self::Gtq => 'Guatemalan Quetzal',
            self::Gyd => 'Guyanese Dollar',
            self::Hkd => 'Hong Kong Dollar',
            self::Hnl => 'Honduran Lempira',
            self::Htg => 'Haitian Gourde',
            self::Huf => 'Hungarian Forint',
            self::Idr => 'Indonesian Rupiah',
            self::Ils => 'Israeli New Shekel',
            self::Inr => 'Indian Rupee',
            self::Iqd => 'Iraqi Dinar',
            self::Irr => 'Iranian Rial',
            self::Isk => 'Icelandic Króna',
            self::Jmd => 'Jamaican Dollar',
            self::Jod => 'Jordanian Dinar',
            self::Jpy => 'Japanese Yen',
            self::Kes => 'Kenyan Shilling',
            self::Kgs => 'Kyrgyzstan Som',
            self::Khr => 'Cambodian Riel',
            self::Kmf => 'Comoro Franc',
            self::Kpw => 'North Korean Won',
            self::Krw => 'South Korean Won',
            self::Kwd => 'Kuwaiti Dinar',
            self::Kyd => 'Cayman Islands Dollar',
            self::Kzt => 'Kazakhstani Tenge',
            self::Lak => 'Lao Kip',
            self::Lbp => 'Lebanese Pound',
            self::Lkr => 'Sri Lankan Rupee',
            self::Lrd => 'Liberian Dollar',
            self::Lsl => 'Lesotho Loti',
            self::Lyd => 'Libyan Dinar',
            self::Mad => 'Moroccan Dirham',
            self::Mdl => 'Moldovan Leu',
            self::Mga => 'Malagasy Ariary',
            self::Mkd => 'Macedonian Denar',
            self::Mmk => 'Myanmar Kyat',
            self::Mnt => 'Mongolian Tögrög',
            self::Mop => 'Macanese Pataca',
            self::Mru => 'Mauritanian Ouguiya',
            self::Mur => 'Mauritian Rupee',
            self::Mvr => 'Maldivian Rufiyaa',
            self::Mwk => 'Malawian Kwacha',
            self::Mxn => 'Mexican Peso',
            self::Mxv => 'Mexican Unidad de Inversión',
            self::Myr => 'Malaysian Ringgit',
            self::Mzn => 'Mozambican Metical',
            self::Nad => 'Namibian Dollar',
            self::Ngn => 'Nigerian Naira',
            self::Nio => 'Nicaraguan Córdoba',
            self::Nok => 'Norwegian Krone',
            self::Npr => 'Nepalese Rupee',
            self::Nzd => 'New Zealand Dollar',
            self::Omr => 'Omani Rial',
            self::Pab => 'Panamanian Balboa',
            self::Pen => 'Peruvian Sol',
            self::Pgk => 'Papua New Guinean Kina',
            self::Php => 'Philippine Peso',
            self::Pkr => 'Pakistani Rupee',
            self::Pln => 'Polish Złoty',
            self::Pyg => 'Paraguayan Guaraní',
            self::Qar => 'Qatari Riyal',
            self::Ron => 'Romanian Leu',
            self::Rsd => 'Serbian Dinar',
            self::Rub => 'Russian Ruble',
            self::Rwf => 'Rwandan Franc',
            self::Sar => 'Saudi Riyal',
            self::Sbd => 'Solomon Islands Dollar',
            self::Scr => 'Seychelles Rupee',
            self::Sdg => 'Sudanese Pound',
            self::Sek => 'Swedish Krona',
            self::Sgd => 'Singapore Dollar',
            self::Shp => 'Saint Helena Pound',
            self::Sle => 'Sierra Leonean Leone',
            self::Sos => 'Somali Shilling',
            self::Srd => 'Surinamese Dollar',
            self::Ssp => 'South Sudanese Pound',
            self::Stn => 'São Tomé and Príncipe Dobra',
            self::Svc => 'Salvadoran Colón',
            self::Syp => 'Syrian Pound',
            self::Szl => 'Swazi Lilangeni',
            self::Thb => 'Thai Baht',
            self::Tjs => 'Tajikistani Somoni',
            self::Tmt => 'Turkmenistan Manat',
            self::Tnd => 'Tunisian Dinar',
            self::Top => 'Tongan Paʻanga',
            self::Try => 'Turkish Lira',
            self::Ttd => 'Trinidad and Tobago Dollar',
            self::Twd => 'New Taiwan Dollar',
            self::Tzs => 'Tanzanian Shilling',
            self::Uah => 'Ukrainian Hryvnia',
            self::Ugx => 'Ugandan Shilling',
            self::Usd => 'United States Dollar',
            self::Usn => 'US Dollar (Next day)',
            self::Uyi => 'Uruguay Peso en Unidades Indexadas',
            self::Uyu => 'Uruguayan Peso',
            self::Uyw => 'Unidad Previsional',
            self::Uzs => 'Uzbekistan Som',
            self::Ved => 'Venezuelan Digital Bolivar',
            self::Ves => 'Venezuelan Sovereign Bolivar',
            self::Vnd => 'Vietnamese Đồng',
            self::Vuv => 'Vanuatu Vatu',
            self::Wst => 'Samoan Tālā',
            self::Xaf => 'Central African CFA Franc',
            self::Xcd => 'East Caribbean Dollar',
            self::Xof => 'West African CFA Franc',
            self::Xpf => 'CFP Franc',
            self::Yer => 'Yemeni Rial',
            self::Zar => 'South African Rand',
            self::Zmw => 'Zambian Kwacha',
            self::Zwg => 'Zimbabwean Dollar',
        };
    }
}
